# Generated by Django 2.0.5 on 2022-03-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_codigo', models.CharField(blank=True, max_length=250)),
                ('d_asenta', models.CharField(blank=True, max_length=10)),
                ('d_tipo_asenta', models.CharField(blank=True, max_length=250)),
                ('D_mnpio', models.CharField(blank=True, max_length=250)),
                ('d_estado', models.CharField(blank=True, max_length=250)),
                ('d_ciudad', models.CharField(blank=True, max_length=250)),
                ('d_CP', models.CharField(blank=True, max_length=250)),
                ('c_estado', models.CharField(blank=True, max_length=250)),
                ('c_oficina', models.CharField(blank=True, max_length=250)),
                ('c_CP', models.CharField(blank=True, max_length=250)),
                ('c_tipo_asenta', models.CharField(blank=True, max_length=250)),
                ('c_mnpio', models.CharField(blank=True, max_length=250)),
                ('id_asenta_cpcons', models.CharField(blank=True, max_length=250)),
                ('d_zona', models.CharField(blank=True, max_length=250)),
                ('c_cve_ciudad', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'db_table': 'crm',
            },
        ),
        migrations.DeleteModel(
            name='Asesoria',
        ),
        migrations.DeleteModel(
            name='Automaquillaje',
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='Empresas',
        ),
        migrations.DeleteModel(
            name='Guia',
        ),
        migrations.DeleteModel(
            name='Informes',
        ),
        migrations.DeleteModel(
            name='Respuestas',
        ),
        migrations.DeleteModel(
            name='Servicios',
        ),
        migrations.DeleteModel(
            name='Suscripcion',
        ),
        migrations.DeleteModel(
            name='Valido',
        ),
    ]
