# Generated by Django 2.2.6 on 2022-03-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20220309_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm',
            name='d_asenta',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
